import type { Metadata } from 'next'
import { Inter, Lusitana } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

import { QueryProvider } from '@/provider/query-provider'
import SheetProvider from '@/provider/sheet-provider'
import { Toaster } from '@/components/ui/sonner'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const lusitana = Lusitana({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children?: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={inter.className}>
          <QueryProvider>
            <SheetProvider />
            <Toaster />
            {children}
          </QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
